version: "3"
services:
  slideshow:
    image: slideshow:latest
    ports:
      - "4100:7777"
    expose:
      - 4100
    environment:
      - SIGNAL_USERNAME=signal
      - SIGNAL_PASSWORD=test
      - SIGNAL_ACCOUNTNO=+4924519329263
      - SIGNAL_OUTPUTFOLDER=/images/
      - SIGNAL_THUMBNAILFOLDER=/thumbnails/
      - SIGNAL_GROUPID=xq+GP2S/+hEAdwSc+9IX6UvUE2sHBAwECMju+pIbbX0=
      - SIGNAL_SIGNALWS=ws://homeassistant.fritz.box:8080/v1/receive/
      - SIGNAL_SIGNALAPI=http://homeassistant.fritz.box:8080/
      - SLIDESHOW_PORT=7777
      - SLIDESHOW_FRONTEND_DIST=/dist/
      - SLIDESHOW_CONFIGDIR=/config/
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    volumes:
      - "./images:/images"
      - "./thumbnails:/thumbnails"
      - "./config:/config"
